---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "toothpick-master.fullname" . }}
  labels:
    {{- include "toothpick-master.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | indent 4 | trim }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $val := .Values.ports }}
    - port: {{ $val.public }}
      targetPort: {{ kebabcase $key }}
      protocol: TCP
      name: {{ required (printf "protocol for port %s is required" $key) $val.protocol }}-{{ kebabcase $key }}
    {{- end }}
  selector:
    {{- include "toothpick-master.selectorLabels" . | nindent 4 }}
