name: Derive branch and tag
description: Derive branch and tag
outputs:
  branch:
    description: Branch
    value: ${{ steps.ref.outputs.branch }}
  tag:
    description: Tag
    value: ${{ steps.ref.outputs.tag }}
runs:
  using: composite
  steps:
    - name: Derive
      id: ref
      shell: bash
      run: |
        BRANCH=""
        TAG=""
        if [[ "${GITHUB_REF}" =~ ^refs/heads/.* ]]; then
          BRANCH=${GITHUB_REF#refs/heads/}
        fi

        if [[ "${GITHUB_REF}" =~ ^refs/tags/.* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
        fi

        echo "::set-output name=branch::${BRANCH}"
        echo "::set-output name=tag::${TAG}"
