---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "env-injector.serviceAccountName" . }}
  labels:
    {{- include "env-injector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "env-injector.fullname" . }}
  labels:
    {{- include "env-injector.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list" , "get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list" , "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "env-injector.fullname" . }}
  labels:
    {{- include "env-injector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "env-injector.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "env-injector.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}