global:
  image:
    repository: public.ecr.aws/g1b1f7a7/toothpick-server
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []

  fdbConnectionStringConfigMap:
    name: ""
    key: connectionString

  serviceMonitor:
    enabled: true
