global:
  image:
    repository: public.ecr.aws/z8i7w3s6/toothpick-server
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []

  fdbConnectionStringConfigMap:
    name: ""
    key: connectionString

  serviceMonitor:
    enabled: true
