apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toothpick-worker.fullname" . }}-app-config
  labels:
    {{- include "toothpick-worker.labels" . | nindent 4 }}
type: Opaque
data:
  "app.conf": {{ .Values.appConfig | toPrettyJson | b64enc }}
