apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toothpick-worker.fullname" . }}-prometheus-jmx-exporter-config
  labels:
    {{- include "toothpick-worker.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: |-
    {{ .Files.Get "prometheus-jmx-exporter-config.yaml" | b64enc }}
