name: CI Workflow

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build-runner:
    name: Build runner
    runs-on: [self-hosted, nix]
    strategy:
      matrix:
        arch:
          - x86_64-linux
          - x86_64-darwin
          - aarch64-darwin    
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      # - name: Decrypt
      #   uses: ./.github/actions/decrypt-git-crypt
      #   with:
      #     gitCryptGpgKey: ${{ secrets.GIT_CRYPT_GPG_KEY }}
      #   timeout-minutes: 2

      - name: Build runner
        run: |-
          nix build -L -v --no-link '.#packages.${{ matrix.arch }}.runnerJre'

      - name: Cache runner
        env: 
          NIX_OUTPUT: .#packages.${{ matrix.arch }}.runnerJre
        run: |
          nix store sign "${NIX_OUTPUT}" -v -r -k ~/.secrets/nix-cache-private-key
          nix copy -v "${NIX_OUTPUT}" --to s3://nixed/cache?profile=nix-cache

  build-images:
    name: Build images
    runs-on: [self-hosted, nix]
    needs: build-runner
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      # - name: Decrypt
      #   uses: ./.github/actions/decrypt-git-crypt
      #   with:
      #     gitCryptGpgKey: ${{ secrets.GIT_CRYPT_GPG_KEY }}
      #   timeout-minutes: 2

      - name: Login to Docker Hub
        uses: docker/login-action@v1  
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: chmod +r ~/.docker/config.json

      - name: Derive branch and tag
        id: meta
        uses: ./.github/actions/derive-branch-tag

      - name: Build container images
        run: |-
          nix build -L -v '.#packages.${{ matrix.arch }}-linux.serverImage' 

      - name: Push
        env:
          GITHUB_TAG: ${{ steps.meta.outputs.tag }}
          GITHUB_SHA: ${{ github.sha }}  
        run: |-
          TAG=${GITHUB_TAG:-"${GITHUB_SHA}"}
          nix develop '.#skopeoShell' -v -c \
            skopeo --insecure-policy copy docker-archive:./result docker://docker.io/shopstic/toothpick-server:${{ matrix.arch }}-"${TAG}"

  push-manifest:
    name: Push multi-arch manifest
    runs-on: [self-hosted, nix]
    needs: build-images
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: chmod +r ~/.docker/config.json

      - name: Derive branch and tag
        id: meta
        uses: ./.github/actions/derive-branch-tag

      - name: Push
        env:
          GITHUB_TAG: ${{ steps.meta.outputs.tag }}
          GITHUB_SHA: ${{ github.sha }}  
        run: |-
          TAG=${GITHUB_TAG:-"${GITHUB_SHA}"}
          docker manifest create \
            shopstic/toothpick-server:"${TAG}" \
            --amend shopstic/toothpick-server:x86_64-"${TAG}" \
            --amend shopstic/toothpick-server:aarch64-"${TAG}"

          docker manifest push shopstic/toothpick-server:"${TAG}"
  
  build-helm-chart:
    name: Build Helm chart
    runs-on: [self-hosted, nix]
    needs: build-images
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: chmod +r ~/.docker/config.json

      - name: Derive branch and tag
        id: meta
        uses: ./.github/actions/derive-branch-tag

      - name: Build and push Helm Chart
        # if: steps.ref_name.outputs.tag != ''
        env:
          GITHUB_TAG: ${{ steps.meta.outputs.tag }}
          GITHUB_SHA: ${{ github.sha }}
        run: |-
          export HELM_REGISTRY_CONFIG=/home/runner/.docker/config.json

          CHART_VERSION=${GITHUB_TAG:-"1.0.0-${GITHUB_SHA}"}
          APP_VERSION=${GITHUB_TAG:-"${GITHUB_SHA}"}

          nix develop '.#helmShell' -v -c ./cli.sh push_helm_chart "${CHART_VERSION}" "${APP_VERSION}" "oci://ghcr.io/shopstic/toothpick/chart"